# Making sense of the total spin operator in the energy levels analogy

$S$ is always thought as the combination of many total spin operators, $S^2$ should have a clear matrix form. 
In this notebook we investigate the behavior of $S^2$ and the analogy that people make with [energy level states](https://coldfusionblog.net/2014/05/19/introduction-to-superradiance/)

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
from qutip import *
import plotly.express as px
import matplotlib.pyplot as plt

In [2]:
sup=Qobj([[1],[0]])
sdw=Qobj([[0],[1]])
sdw

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [24]:
sx=0.5*Qobj([[0, 1],[1, 0]])      #also 0.5*sigmax()
sy=0.5*Qobj([[0, -1j],[+1j, 0]])
sz=0.5*Qobj([[1,0],[0,-1]])


Once we created the conventional Spin projection matrices $S_i$, we can make the $S^2$

In [26]:
s2=sx**2 + sy**2 + sz**2
s2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.75 0.  ]
 [0.   0.75]]

In [23]:
sup=fock(2,1)      #"excited" fock state that conventionally is spin down here

sup.dag()*sz*sup   #explicit expectation value
expect(sz,sup)     #Qutip function for expectation value

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[-0.5]]

## Now we are ready to make a tensor product and produce a simple hamiltonian
$$H = \sum_ {i}S_z ^{(i)}$$

In this representation:  $$ 1/2 \otimes 1/2$$

In [8]:
sz_1=tensor(sz,qeye(2))
sz_2=tensor(qeye(2),sz)
H = sz_1 + sz_2
H

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]]

Now $H$ is the total $S_z=S_z^{(i)} +S_z^{(2)}$

## N.B. : in QuTip, excited 2D (fock) states are those with spin down

In [9]:
ssz=H
psi=tensor(basis(2,0), basis(2,0))
psi

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

## Average value of $S_z$ in a composite state (tensor product state)

In [10]:
psi.dag() * ssz * psi

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[1.]]

## A general quantum state of the vector product of two spin 1/2 particles as a linear combination

In [11]:
uu=tensor(basis(2,0), basis(2,0))
ud=tensor(basis(2,0), basis(2,1))    #all combinations
du=tensor(basis(2,1), basis(2,0))
dd=tensor(basis(2,1), basis(2,1))

a=1j   #coefficients for all combinations
b=1
c=0
d=0

psig= (a*uu + b*ud + c*du + d*dd).unit()
psig



Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.70710678j]
 [0.70710678+0.j        ]
 [0.        +0.j        ]
 [0.        +0.j        ]]

## Average value of $S_z$ in a general state

In [12]:
psig.dag() * ssz * psig   

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.5]]

# Now we want to find the matrix representation of the operator $S^2$

According to these [lecture notes](https://ocw.mit.edu/courses/physics/8-05-quantum-physics-ii-fall-2013/lecture-notes/MIT8_05F13_Chap_10.pdf), eq. 2.9, 
$$1 \oplus 0 = 1/2 \otimes 1/2$$ 
we want find the right matrix representation for for a sum of angular momenta as described in eq. 2.19.


In [13]:
sigmam()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [1. 0.]]

In [14]:
ssz
ssx= tensor(sx,qeye(2)) + tensor(qeye(2),sx)
ssy= tensor(sy,qeye(2)) + tensor(qeye(2),sy)

ss2= ssx**2 + ssy**2 + ssz**2 # + 2* tensor(sx,qeye(2)) * tensor(qeye(2),sx)  +  tensor(sigmam(),qeye(2)) * tensor(qeye(2),sigmap()) + tensor(sigmap(),qeye(2)) * tensor(qeye(2),sigmam())   
ss2  #here is the total spin operator  

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[2. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 2.]]

This operator should allow to understand when a state is in an eigenstate of the total angular momentum: as you see it is not diagonal, it means that in this representation $|1>\otimes |2>$ needs to be rotated in order to have a diagonal (degenerate) $S^2$

In [15]:
evals, ekets = ss2.eigenstates()
evals

array([1.11022302e-15, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00])

In [16]:
ekets[0]

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]

In [17]:
(ud.dag()*ekets[0])*(ekets[0].dag()*ud)

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.5]]

# $1 \oplus 0 = 1/2 \otimes 1/2$  : we should find the right representation for this

In [18]:
jmat(0, '-')

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [19]:
sigmam()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0. 0.]
 [1. 0.]]

In [20]:
kk=(tensor(sx,qeye(2)) + tensor(qeye(2),sx))**2
kk

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.5 0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.5 0.  0.  0.5]]

In [21]:
kk=tensor(sx,qeye(2))**2 + tensor(qeye(2),sx)**2
kk

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0. ]
 [0.  0.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  0.5]]