# Making sense of the total spin operator in the energy levels analogy

$S$ is always thought as the combination of many total spin operators, $S^2$ should have a clear matrix form. 
In this notebook we investigate the behavior of $S^2$ and the analogy that people make with [energy level states](https://coldfusionblog.net/2014/05/19/introduction-to-superradiance/)

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
from qutip import *
import plotly.express as px
import matplotlib.pyplot as plt

In [3]:
sup=Qobj([[1],[0]])
sdw=Qobj([[0],[1]])
sdw

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

In [4]:
sx=0.5*Qobj([[0, 1],[1, 0]])
sx

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.  0.5]
 [0.5 0. ]]

In [5]:
sy=0.5*Qobj([[0, -1j],[+1j, 0]])
sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j  0.-0.5j]
 [0.+0.5j 0.+0.j ]]

In [6]:
sz=0.5*Qobj([[1,0],[0,-1]])
sz

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5  0. ]
 [ 0.  -0.5]]

Once we created the conventional Spin projection matrices $S_i$, we can make the $S^2$

In [7]:
s2=sx*sx + sy*sy + sz*sz
s2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.75 0.  ]
 [0.   0.75]]

In [35]:
sup=fock(2,1)

sup.dag()*sz*sup

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[-0.5]]

## Now we are ready to make a tensor product and produce a simple hamiltonian
$$H = \sum_ {i}S_z ^{(i)}$$

In [8]:
sz_1=tensor(sz,qeye(2))
sz_2=tensor(qeye(2),sz)
H = sz_1 + sz_2
H

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -1.]]

But $H$ now seems to be the total $S_z=S_z^{(i)} +S_z^{(2)}$

## N.B. : in QuTip, excited 2D (fock) states are those with spin down

In [37]:
ssz=H
psi=tensor(basis(2,0), basis(2,0))
psi

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

## Average value of $S_z$ in a composite state (tensor product state)

In [38]:
psi.dag() * ssz * psi

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[1.]]

A general quantum state of the vector product of two spin 1/2 particles as a linear combination

In [75]:
uu=tensor(basis(2,0), basis(2,0))
ud=tensor(basis(2,0), basis(2,1))    #all combinations
du=tensor(basis(2,1), basis(2,0))
dd=tensor(basis(2,1), basis(2,1))

a=Qobj([[2]])   #coefficients for all combinations
b=Qobj([[1]])
c=Qobj([[-3]])
d=Qobj([[0]])

psig= (a*uu + b*ud + c*du + d*dd).unit()
psig



Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.53452248]
 [ 0.26726124]
 [-0.80178373]
 [ 0.        ]]


Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.28571429]]

## Average value of $S_z$ in a general state

In [76]:
psig.dag() * ssz * psig   

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.28571429]]